### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by iamlogiq** [tadija/AEIconizer#11]
Great plugin but I was wondering it you plan on updating to include the new apple watch size. I would also love to see a way to automatically set the filename suffix and file type for each size exports. I find that I have to manually set the export setting + I have to add the suffix to include the size.

**Comment by tadija** [comment]
Thanks. There's a new version now, which supports watchOS icon sizes.

I'm not sure I understood what's your problem with exporting, when I run the plugin,
it selects all created artboards, then I just click on 'Make Exportable' button and go to menu File / Export,
then everything is ready to just save all files (including size in filename) as PNG (which I want) and that's it. Doesn't that work for you?

**Comment by iamlogiq** [comment]
@tadija It was my mistake...I should have been using multiple art-boards. Thanks for the update with the Apple Watch sizes!
