### ISSUE TITLE
Doesn't work on Sketch 3.6.x 

### ISSUE THREAD

**Issue by kukushi** [tadija/AEIconizer#13]
Hi, tadija, you really do a good job. 
But after update Sketch to 3.6, the AEIconizer doesn't generate the icons in the right way(something like misplacement). Any plan on fix that?

**Comment by mathshane** [comment]
I noticed this as well -- was just about to report it here.

I think Sketch changed the layout of the iOS App icon template.

**Comment by SpencerLynn** [comment]
Doesn't appear to work with 3.7.2 either. The Mac App icon template workaround doesn't appear to work in this version either.

**Comment by madnik** [comment]
What is the normal workflow you guys use until plugin is fixed for new template?

**Comment by tadija** [comment]
Hi, I don't really understand what is not working? I've just tried in Sketch 3.7.2 and it works as usual.
It never had any relation with built in icon templates, you just create new blank file, add square artboard, draw icon inside and run the plugin. Can you post some screenshots?

**Comment by zilos** [comment]
yeah its not working for me either. the plugin doesnt even show up in the plugins menu.

**Comment by zbrowne** [comment]
I've had a similar issue. It worked before I upgraded and now in version 3.7.2 it is not working. I will try to start from scratch with a new file and see if the issue persists. The current screenshot is made up of a red circle object and two symbols (long black line and short black lines). Please let me know if further information will help. 
![screen shot 2016-05-06 at 5 13 41 pm](https://cloud.githubusercontent.com/assets/7422697/15088880/404f74d4-13ae-11e6-87d7-8c98ccf75d96.png)

**Comment by tadija** [comment]
Hmm, I've just reproduced some strange behaviour - plugin works properly only if it's used on 'Page 1' of the Sketch document. On other pages artboards are messed up. 

May some of you confirm that this is the problem? @kukushi @mathshane @SpencerLynn @madnik @zilos @zbrowne

**Comment by zbrowne** [comment]
I renamed the page "Page 1" and it is still producing the identical behavior highlighted above. I also created a new file and copied the existing icon into the new file on the default "Page 1" page and still no changes.

**Comment by zbrowne** [comment]
any updates on why it's not working or suggestions I should reproduce?

**Comment by tadija** [comment]
Well not really unfortunately, but I can confirm that I recreated identical example as yours in a new document on the first page and it worked ok.

**Comment by zilos** [comment]
looks like the plugin is working fine for me now. No idea what happened or how it got fixed.

**Comment by kukushi** [comment]
@tadija Sorry for late reply. It's basic how it look like.
<img width="1038" alt="screen shot 2016-06-07 at 12 47 12 am" src="https://cloud.githubusercontent.com/assets/2424654/15830179/8c863e7e-2c49-11e6-8b7a-0579a95c5225.png">

**Comment by tadija** [comment]
Hi @kukushi, this plugin is not intended to be used with iOS App Icon template from Sketch but rather with just empty Sketch file. Check out latest version (2.2.2), I hope it works for you!

**Comment by edpenano** [comment]
Anyone having issues in ver. 46.2 of sketch?
