### ISSUE TITLE
New Sizes for imessage app

### ISSUE THREAD

**Issue by SirDwar** [tadija/AEIconizer#17]
Is it possible to create new sizes for the imessage apps?
According to Xcode:
 icon-messages-app-27x20@1x.png

Messages

icon-messages-app-27x20@2x.png

Messages

icon-messages-app-27x20@3x.png

Messages

icon-messages-app-iPadAir-67x50@2x.png

iPad Messages

icon-messages-app-iPadAir-74x55@2x.png

iPad Pro Messages

icon-messages-app-iPhone-60x45@1x.png

Old iPhone Messages

icon-messages-app-iPhone-60x45@2x.png

iPhone 6S, iPhone 6, iPhone 5S, iPhone 5, iPhone SE Messages

icon-messages-app-iPhone-60x45@3x.png

iPhone 6S Plus, iPhone 6 Plus Messages

icon-messages-transcript-32x24@1x.png

Messages

icon-messages-transcript-32x24@2x.png

Messages

icon-messages-transcript-32x24@3x.png

Messages

icon-messages-appicon-1024x768@3x.png

Messages App Store

Thx

Eddy

**Comment by tadija** [comment]
Hi, thanks for the proposal, but I don't think it would be very useful thing to do for icons with different aspect ratio then 1:1 so that's probably not gonna be supported with this plugin.
