### ISSUE TITLE
Please update guides for iOS 8.x and new devices

### ISSUE THREAD

**Issue by arudmin** [tadija/AEIconizer#2]
Please take a look at these links:
https://gist.github.com/tfausak/2222823
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW1

Thank you.

**Comment by tadija** [comment]
Ok, so which exactly app icon size is not currently supported?
