### ISSUE TITLE
Blurry/distorted Icons

### ISSUE THREAD

**Issue by MillerApps** [tadija/AEIconizer#20]
After running the plugin the icons of smaller size are blurry/distorted, see the image below. 

Sketch Version 40 (33762)

![screen shot 2016-09-21 at 10 20 00 pm](https://cloud.githubusercontent.com/assets/3836934/18735177/e05bcf2e-8049-11e6-8556-1189198c6a9d.png)
.

**Comment by kevinbluer** [comment]
@MillerApps It appears to just be the case with PNGs (and possibly other flat image files) within icons. Seems ok when resizing with pure embedded SVGs. Not sure if that helps in the immediate terms (until a fix comes along).

**Comment by MillerApps** [comment]
@kevinbluer I'm not using any PNGs or flat image files.

**Comment by tadija** [comment]
I'm sorry, but I don't really understand what's the problem here.
