### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by justdan0227** [tadija/AEIconizer#22]
How do you install this?

**Comment by djspider88** [comment]
Just double click the AEIconizer.sketchplugin file once downloaded and it should automatically install for you 👍

**Comment by codicil** [comment]
So this plugin works with what, i mean can you list the action item to make it run, sorry for asking raw question as I am very new to this platform and icon world

I download the latest release of zip file and when clicked AEIconizer.cocoascript dialogue box cam saying  is saying 
Xcode is being updated
Xcode can not be opened while it is being updated.

does this file open in Xcode once update is complete?

**Comment by tadija** [comment]
Try to install with http://sketchtoolbox.com.
