### ISSUE TITLE
Half-pixel sizes

### ISSUE THREAD

**Issue by hannahlcampbell** [tadija/AEIconizer#23]
The artboards for Icon-83.5 and Icon-27.5 round up to the nearest integer. This is a problem when exporting since the 2x export is one pixel larger than required. Is there a setting in Sketch to allow the half-pixel?

**Comment by squarefrog** [comment]
It's probably worth just creating the Icon-83.5@2x manually - e.g. create a 167x167 artboard and naming that Icon-83.5@2x. As this size is only used on the iPad Pro, I don't think theres any point creating the 1x and 3x.

**Comment by zippo227** [comment]
Has this size been added? I don't see it in the version I downloaded today.

**Comment by tadija** [comment]
This should be fixed now in the latest version (2.3.0).
Half-pixel sizes are now created only in @2x.
