### ISSUE TITLE
Notification 20pt size

### ISSUE THREAD

**Issue by tylerswartz** [tadija/AEIconizer#26]
Hey There - First off, thanks for making this super helpful plugin!

xCode now has a place for a 20pt icon ("iPhone notification, iOS 7 - 10"). I don't see a 20pt in the export sizes. I'm not sure when they added this requirement. For the time being I put the 24pt icon in it's place, but I do get a warning from xcode that the size is incorrect. 

Can you add this as an export size?

```
Asset Catalog -> Icon-24@3x.png is 72x72 but should be 60x60
Asset Catalog -> Icon-24@2x.png is 48x48 but should be 40x40
```

**Comment by tadija** [comment]
Hi, look again, 20pt size is also there! :)

**Comment by tylerswartz** [comment]
I think I must be on an older version then since I don't see it. I'll upgrade. thanks
