### ISSUE TITLE
Not working on Sketch 44.1

### ISSUE THREAD

**Issue by betancur** [tadija/AEIconizer#29]
It only renames the original artboard to Icon-Original, but not create any additional ArtBoard.

**Comment by tadija** [comment]
Latest version of AEIconizer should work with Sketch 44.1.
Please check again if you're using the latest version of this plugin.

**Comment by edpenano** [comment]
@betancur - where you able to this resolved? If so, could you please let me know what you did? I'm currently running Sketch 46. I am running Mac High Sierra Beta, so not sure if this is the cause of issue. Any leads would be greatly appreciated. Thank you!
