### ISSUE TITLE
Inconsistent results for some layers

### ISSUE THREAD

**Issue by acahir** [tadija/AEIconizer#30]
Are there any tricks to ensure accurate generation of the different icon sizes?

When I run the plugin, most of the image look correct, but a group involving a repeating symbol does not seem to be scaled down correctly. 

I admit to being new with Sketch, so could be something I've done.

**Comment by tadija** [comment]
To be honest, I'm not sure what could be the problem there. Plugin works by just scaling entire artboard to different sizes, same as if you would manually select artboard then click on scale option, you might wanna try that just to check if the result is same.

**Comment by acahir** [comment]
Yea, I played with it for a while and the results did seem to be inconsistent, although I'm not sure why. I ended up recreating the layers with rectangles instead of lines, which seems to scale better. 

Thanks
