### ISSUE TITLE
2.4 with Sketch 43.2

### ISSUE THREAD

**Issue by richardlevy** [tadija/AEIconizer#34]
Hi

I'm trying to use AEIconizer with Sketch 43.2 and I just get the 512 icon.

Can you recommend a plugin version for Sketch 43.2?

Thanks
Rich

**Comment by tadija** [comment]
Hi,

by comparing data at https://www.sketchapp.com/updates/ with commit messages here, I'd try with plugin version 2.1.0 or 2.2.0.
