### ISSUE TITLE
Not working on macOS 10.13.2 Sketch 48.1

### ISSUE THREAD

**Issue by PabloHenri91** [tadija/AEIconizer#36]
No error message on script run but the plugin does nothing.

**Comment by tadija** [comment]
How do you use it? I tried it on these same versions and it's working.

**Comment by PabloHenri91** [comment]
- Clone repo
- double click on AEIconizer.sketchplugin
- Click Replace
- Open Sketch
- Click New Document
- Press A
- Drag the mouse to create an artboard
- Change artboard size to have equal width and height
- Press O
- Drag the mouse to draw an oval
- Select the artboard
-Click Plugins, AEIconizer, AEIconizer
![screen shot 2017-12-15 at 13 21 13 2](https://user-images.githubusercontent.com/7740867/34048450-e06d669a-e19a-11e7-81b9-28c3f56dedd1.png)

**Comment by SketchySwift** [comment]
when will this plugin be updated. I really need it, it's a lifesaver!

**Comment by tadija** [comment]
Sorry, I checked again and it's working in the latest version of Sketch (51.3), maybe you need some specific version of plugin which worked with older version of Sketch...
