### ISSUE TITLE
iPad Pro Icon size.

### ISSUE THREAD

**Issue by EmperiorEric** [tadija/AEIconizer#5]
The iPad Pro introduces a new Icon size.

167x167 pixels @2x

**Comment by youngbobby** [comment]
Hi,

Please add support for new iPad Pro icon size 83.5x83.5 @2x like @EmperiorEric mentioned above.

Thanks.

**Comment by EmperiorEric** [comment]
Looks like there are now two pull requests #6 and #7 that would fix this for us. Just need them merged.

**Comment by tadija** [comment]
Hi, thanks for the feedback, #7 is merged now, so this can be closed.
